import { Shield, Eye, ShieldCheck, Lock, Terminal, UserCheck } from 'lucide-react'

const SECURITY_CARDS = [
  {
    icon: Lock,
    title: 'Workspace Isolation',
    desc: 'All databases, uploaded documents, and investigation plans are scoped tightly to your workspace. Isolation boundaries prevent data leaks between organizational teams.'
  },
  {
    icon: Terminal,
    title: 'Controlled Sandbox Execution',
    desc: 'Python scripts generated by DataPilot run in isolated, serverless sandboxes. Execution limits prevent infinite loops, resource leaks, and unauthorized outbound requests.'
  },
  {
    icon: ShieldCheck,
    title: 'Sensitive Data Awareness',
    desc: 'Automatic detection of PII (names, emails, phone numbers) before datasets are profiled. DataPilot handles fields using local hashing or masking rules to protect customer privacy.'
  },
  {
    icon: Eye,
    title: 'Evidence Transparency',
    desc: 'No hidden black-box reasoning. Every final claim links back to SQL logs, retrieved document chunks, or dataset metrics so your compliance teams can verify the lineage.'
  },
  {
    icon: UserCheck,
    title: 'Human-in-the-Loop Control',
    desc: 'Decisions such as modifying dataset structures or running multi-agent tasks on production pipelines are subject to approval. The supervisor agent is designed as an assistant, not an autocrat.'
  }
]

export default function SecuritySection() {
  return (
    <section id="security" className="py-24 bg-[#080812] relative overflow-hidden border-t border-[#181830]">
      {/* Background visual graphics */}
      <div className="absolute left-1/2 bottom-0 -translate-x-1/2 w-[800px] h-[300px] bg-indigo-500/5 rounded-full blur-[140px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="text-xs font-semibold px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 uppercase tracking-wider">
            SECURITY & GOVERNANCE
          </span>
          <h2 className="text-3xl sm:text-5xl font-extrabold text-slate-100 mt-4 tracking-tight">
            Built with control in mind.
          </h2>
          <p className="mt-4 text-base sm:text-lg text-slate-400">
            Enterprise data analysis demands security at every tier. DataPilot is engineered with strict isolation, sandboxed computing, and audit log transparency.
          </p>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {SECURITY_CARDS.map((card, idx) => {
            const Icon = card.icon
            // Render the last card full-width on lg screens if it is the 5th card, or make it span 2 columns
            const spanClass = idx === 4 ? 'lg:col-span-2' : ''
            return (
              <div
                key={card.title}
                className={`p-6 rounded-2xl bg-[#0e0e1c]/80 border border-[#1e1e3b] hover:border-indigo-500/40 hover:bg-[#121226]/90 transition-all duration-300 group flex flex-col justify-between shadow-lg ${spanClass}`}
              >
                <div>
                  <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400 group-hover:scale-105 transition-transform duration-300">
                    <Icon size={20} />
                  </div>
                  <h3 className="text-base font-bold text-slate-100 mt-5 tracking-wide">{card.title}</h3>
                  <p className="text-xs text-slate-400 leading-relaxed mt-2.5">{card.desc}</p>
                </div>
                
                <div className="mt-6 pt-3 border-t border-[#1b1b36] flex items-center justify-between text-[10px] font-mono text-slate-500">
                  <span>DataPilot Core Spec</span>
                  <span className="text-indigo-400 group-hover:underline">Active Policy</span>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
